# numbers = [16,7,8,9,4,55,]
# numbers2 = [2,5,7,3,2,677,5]

# largestNum = max(numbers)
# print(largestNum)


# even_num = []
# odd_num = []

# for num in numbers:
#     if num % 2 == 0:
#         even_num.append(num)
#     else :
#          odd_num.append(num)

# print(numbers)
# print(even_num)
# print(odd_num)


# new_list = numbers + numbers2

# new_list.sort()
# print("merged and sorted lists are : ", new_list)

# fruits = ["apple", "kiwi", "banana", "orange", "mango"]
 
# fruits.sort(key=len)
# print("sorted fruits by length : ", fruits)


# str = "Hey How are you ?"
# print(str[1])
# print(str[-14])
# print(str[14])
# print(str[-1])
# print(type(str))

# number11 = [1,2,3,6,7,8,9,10]
# number11.append(5)
# print(number11)
# print(type(number11))

# numbers = [1, 2, 3]
# numbers.append(4)
# print(numbers)
# num = numbers.copy()
# print(num)

num1 = [1,2,3,4,5,6,7,8,9,10 , [5 , 7,45,67,89] ]
num1[2] = 500
num2 = num1.copy()
print(num2)
